# Generated by Django 5.0.3 on 2024-03-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='github_url',
            field=models.URLField(null=True),
        ),
    ]
